# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }} >>$GITHUB_OUTPUT
        echo ${{ steps.ip.outputs.ipv6 }} >>$GITHUB_OUTPUT

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v -o ./app .

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}

    - name: Run
      run: ./app
